// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/rate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           float64                `protobuf:"fixed64,1,opt,name=ask,proto3" json:"ask,omitempty"`
	Bid           float64                `protobuf:"fixed64,2,opt,name=bid,proto3" json:"bid,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateResponse) Reset() {
	*x = RateResponse{}
	mi := &file_api_proto_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResponse) ProtoMessage() {}

func (x *RateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResponse.ProtoReflect.Descriptor instead.
func (*RateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rate_proto_rawDescGZIP(), []int{0}
}

func (x *RateResponse) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *RateResponse) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *RateResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rate_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_rate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_rate_proto_rawDescGZIP(), []int{2}
}

var File_api_proto_rate_proto protoreflect.FileDescriptor

const file_api_proto_rate_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/rate.proto\x12\x05proto\"P\n" +
	"\fRateResponse\x12\x10\n" +
	"\x03ask\x18\x01 \x01(\x01R\x03ask\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\x01R\x03bid\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\a\n" +
	"\x05Empty2p\n" +
	"\vRateService\x12-\n" +
	"\bGetRates\x12\f.proto.Empty\x1a\x13.proto.RateResponse\x122\n" +
	"\vHealthCheck\x12\f.proto.Empty\x1a\x15.proto.HealthResponseB\x10Z\x0eusdt/api/protob\x06proto3"

var (
	file_api_proto_rate_proto_rawDescOnce sync.Once
	file_api_proto_rate_proto_rawDescData []byte
)

func file_api_proto_rate_proto_rawDescGZIP() []byte {
	file_api_proto_rate_proto_rawDescOnce.Do(func() {
		file_api_proto_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rate_proto_rawDesc), len(file_api_proto_rate_proto_rawDesc)))
	})
	return file_api_proto_rate_proto_rawDescData
}

var file_api_proto_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_rate_proto_goTypes = []any{
	(*RateResponse)(nil),   // 0: proto.RateResponse
	(*HealthResponse)(nil), // 1: proto.HealthResponse
	(*Empty)(nil),          // 2: proto.Empty
}
var file_api_proto_rate_proto_depIdxs = []int32{
	2, // 0: proto.RateService.GetRates:input_type -> proto.Empty
	2, // 1: proto.RateService.HealthCheck:input_type -> proto.Empty
	0, // 2: proto.RateService.GetRates:output_type -> proto.RateResponse
	1, // 3: proto.RateService.HealthCheck:output_type -> proto.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_rate_proto_init() }
func file_api_proto_rate_proto_init() {
	if File_api_proto_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rate_proto_rawDesc), len(file_api_proto_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rate_proto_goTypes,
		DependencyIndexes: file_api_proto_rate_proto_depIdxs,
		MessageInfos:      file_api_proto_rate_proto_msgTypes,
	}.Build()
	File_api_proto_rate_proto = out.File
	file_api_proto_rate_proto_goTypes = nil
	file_api_proto_rate_proto_depIdxs = nil
}
